Uppercased constants + env vars for readability

diff --git a/.github/workflows/update-root-usercount-jsd-shields-weekly.yml b/.github/workflows/update-root-usercount-jsd-shields-weekly.yml
--- a/.github/workflows/update-root-usercount-jsd-shields-weekly.yml
+++ b/.github/workflows/update-root-usercount-jsd-shields-weekly.yml
@@ -20,7 +20,7 @@ jobs:
 
       - name: Fetch/sum user + JSD request counts
         run: |
-          declare -A gf_scripts=( # for Greasy Fork script user counts
+          declare -A GF_SCRIPTS=( # for Greasy Fork script user counts
             ["460805"]="Autoclear ChatGPT History"
             ["500663"]="AmazonGPT"
             ["462440"]="BraveGPT"
@@ -33,7 +33,7 @@ jobs:
             ["478597"]="GoogleGPT"
           )
 
-          declare -A chrome_extensions=( # for Chrome extension user counts
+          declare -A CHROME_EXTENSIONS=( # for Chrome extension user counts
             ["lbojnhaafilddefkdgmbplkafnckaoga"]="ChatGPT Auto-Continue"
             ["amikeononomkhphopbflomhnmdijjpmb"]="ChatGPT Infinity"
             ["jgnjpnmofkalfliddjelaciggjgnphgm"]="ChatGPT Widescreen Mode"
@@ -41,7 +41,7 @@ jobs:
             ["ckhgddjdjkphbaediggjdddjdjgkalom"]="Perplexity Omnibox"
           )
 
-          declare -A ff_addons=( # for Firefox add-on daily user counts
+          declare -A FF_ADDONS=( # for Firefox add-on daily user counts
             ["brave-omnibox"]="Brave Omnibox"
             ["chatgpt-auto-continue"]="ChatGPT Auto-Continue"
             ["chatgpt-infinity"]="ChatGPT Infinity"
@@ -50,13 +50,13 @@ jobs:
             ["you-com-omnibox"]="You.com Omnibox"
           )
 
-          declare -A edge_addons=( # for Edge addon user counts
+          declare -A EDGE_ADDONS=( # for Edge addon user counts
             ["kaicnimcjamamnlbaeaneofmdjibgepl"]="ChatGPT Auto-Continue"
             ["jgonecnbmehicpdpjkdekamhmlebfagb"]="ChatGPT Infinity"
             ["obnaaalnokmchdoagnhmllakaclaaooa"]="ChatGPT Widescreen Mode"
           )
 
-          jsd_gh_repos=( # for jsDelivr request counts
+          JSD_GH_REPOS=( # for jsDelivr request counts
             "adamlui/ai-web-extensions"
             "adamlui/autoclear-chatgpt-history"
             "adamlui/brave-omnibox"
@@ -110,7 +110,7 @@ jobs:
           }
 
           # Alphabetize arrays for more readable logging
-          for array_type in "gf_scripts" "chrome_extensions" "edge_addons" "ff_addons" ; do
+          for array_type in "GF_SCRIPTS" "CHROME_EXTENSIONS" "EDGE_ADDONS" "FF_ADDONS" ; do
 
             # Extract IDs/names
             eval ids=\${!$array_type[@]} names=(\"\${$array_type[@]}\")
@@ -127,7 +127,7 @@ jobs:
           done
 
           # Fetch/sum Greasy Fork user counts
-          for tuple in "${sorted_gf_scripts[@]}" ; do
+          for tuple in "${sorted_GF_SCRIPTS[@]}" ; do
             script_id="${tuple##*:}" script_name="${tuple%%:*}"
             base_url="https://img.shields.io/greasyfork/dt/"
             gf_users=$(curl -s "$base_url$script_id" |
@@ -138,7 +138,7 @@ jobs:
           done ; echo -e "\n-----\nTotal Greasy Fork users: $total_gf_users\n-----\n"
 
           # Fetch/sum Chrome weekly user counts
-          for tuple in "${sorted_chrome_extensions[@]}" ; do
+          for tuple in "${sorted_CHROME_EXTENSIONS[@]}" ; do
             app_id="${tuple##*:}" app_name="${tuple%%:*}"
             base_url="https://img.shields.io/chrome-web-store/users/"
             chrome_users=$(curl -s "$base_url$app_id" |
@@ -149,7 +149,7 @@ jobs:
           done ; echo -e "\n-----\nTotal Chrome users: $total_chrome_users\n-----\n"
 
           # Fetch/sum FF daily user counts
-          for tuple in "${sorted_ff_addons[@]}" ; do
+          for tuple in "${sorted_FF_ADDONS[@]}" ; do
             app_id="${tuple##*:}" app_name="${tuple%%:*}"
             base_url="https://addons.mozilla.org/api/v5/addons/addon/"
             ff_users=$(curl -s "$base_url$app_id/" |
@@ -159,7 +159,7 @@ jobs:
           done ; echo -e "\n-----\nTotal Firefox users: $total_ff_users\n-----\n"
 
           # Fetch/sum Edge user counts
-          for tuple in "${sorted_edge_addons[@]}" ; do
+          for tuple in "${sorted_EDGE_ADDONS[@]}" ; do
             app_id="${tuple##*:}" app_name="${tuple%%:*}"
             base_url="https://microsoftedge.microsoft.com/addons/getproductdetailsbycrxid/"
             edge_users=$(curl -s "$base_url$app_id" |
@@ -170,7 +170,7 @@ jobs:
           done ; echo -e "\n-----\nTotal Edge users: $total_edge_users\n-----\n"
 
           # Fetch/sum jsDelivr request counts
-          for repo in "${jsd_gh_repos[@]}" ; do
+          for repo in "${JSD_GH_REPOS[@]}" ; do
             repo_requests=$(curl -s "https://img.shields.io/jsdelivr/gh/hm/$repo.svg" |
               sed -n -E 's|.*<title>jsdelivr: ([0-9,.km]+).*</title>.*|\1|Ip')
             repo_requests=$(expand_num "$repo_requests")
@@ -179,46 +179,46 @@ jobs:
           done ; echo -e "\n-----\nTotal monthly jsDelivr requests: $total_requests\n-----\n"
 
           # Format totals
-          formatted_total_users=$(format_total "$((
+          FORMATTED_TOTAL_USERS=$(format_total "$((
             total_gf_users + total_chrome_users + total_ff_users + total_edge_users))")
-          echo "Formatted total users: $formatted_total_users"
-          formatted_total_requests=$(format_total "$total_requests")
-          echo "Formatted total monthly jsDelivr requests: $formatted_total_requests"
+          echo "Formatted total users: $FORMATTED_TOTAL_USERS"
+          FORMATTED_TOTAL_REQUESTS=$(format_total "$total_requests")
+          echo "Formatted total monthly jsDelivr requests: $FORMATTED_TOTAL_REQUESTS"
 
           # Expose totals for update step next
-          echo "total_users=$formatted_total_users" >> $GITHUB_ENV
-          echo "total_requests=$formatted_total_requests" >> $GITHUB_ENV
+          echo "TOTAL_USERS=$FORMATTED_TOTAL_USERS" >> $GITHUB_ENV
+          echo "TOTAL_REQUESTS=$FORMATTED_TOTAL_REQUESTS" >> $GITHUB_ENV
 
       - name: Update README shields
         run: |
           cd ${{ github.workspace }}/adamlui/ai-web-extensions
 
-          total_users="${{ env.total_users }}"
-          total_requests="${{ env.total_requests }}"
+          TOTAL_USERS="${{ env.TOTAL_USERS }}"
+          TOTAL_REQUESTS="${{ env.TOTAL_REQUESTS }}"
 
           # Update usercount shields
-          if [ "$total_users" == "0" ] ; then echo "Error getting total usercount"
+          if [ "$TOTAL_USERS" == "0" ] ; then echo "Error getting total usercount"
           else
             for readme in $(find docs/ -name "README.md") ; do
               old_readme=$(<"$readme")
-              sed -i -E "s|(badge/[^-]+-)[0-9.,km+]+([^?]+\?logo=weightsandbiases)|\1$total_users\2|gI" "$readme"
+              sed -i -E "s|(badge/[^-]+-)[0-9.,km+]+([^?]+\?logo=weightsandbiases)|\1$TOTAL_USERS\2|gI" "$readme"
               new_readme=$(<"$readme")
               if [ "$old_readme" != "$new_readme" ] ; then users_updated=true ; fi
             done
-            if [ "$users_updated" = true ] ; then echo "Usercount shields updated to $total_users"
+            if [ "$users_updated" = true ] ; then echo "Usercount shields updated to $TOTAL_USERS"
             else echo "Usercount shields already up-to-date" ; fi
           fi
 
           # Update jsDelivr shields
-          if [ "$total_requests" == "0" ] ; then echo "Error getting total jsDelivr requests"
+          if [ "$TOTAL_REQUESTS" == "0" ] ; then echo "Error getting total jsDelivr requests"
           else
             for readme in $(find docs/ -name "README.md") ; do
               old_readme=$(<"$readme")
-              sed -i -E "s|(badge/jsDelivr_[^-]+-)[0-9.,km+]+|\1$total_requests|Ig" "$readme"
+              sed -i -E "s|(badge/jsDelivr_[^-]+-)[0-9.,km+]+|\1$TOTAL_REQUESTS|Ig" "$readme"
               new_readme=$(<"$readme")
               if [ "$old_readme" != "$new_readme" ] ; then requests_updated=true ; fi
             done
-            if [ "$requests_updated" = true ] ; then echo "jsDelivr shields updated to $total_requests"
+            if [ "$requests_updated" = true ] ; then echo "jsDelivr shields updated to $TOTAL_REQUESTS"
             else echo "jsDelivr shields already up-to-date" ; fi
           fi
 
@@ -229,18 +229,18 @@ jobs:
           if [ "$shield_types_updated" -gt 1 ] ; then multi_shield_types_updated=true ; fi
 
           # Define commit msg for push step next
-          commit_msg="Updated "
-          [ "$users_updated" = true ] && commit_msg+="usercount"
+          COMMIT_MSG="Updated "
+          [ "$users_updated" = true ] && COMMIT_MSG+="usercount"
           if [ "$requests_updated" = true ] ; then            
-             [ "$multi_shield_types_updated" = true ] && commit_msg+="/" ; commit_msg+="jsDelivr" ; fi
-          commit_msg+=" shield counters in root READMEs"
-          echo "commit_msg=$commit_msg" >> $GITHUB_ENV # expose for push step
+             [ "$multi_shield_types_updated" = true ] && COMMIT_MSG+="/" ; COMMIT_MSG+="jsDelivr" ; fi
+          COMMIT_MSG+=" shield counters in root READMEs"
+          echo "COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV # expose for push step
 
-          # Set Updated flag to check in subseuqent steps
-          if [ "$shield_types_updated" -gt 0 ] ; then echo "shields_updated=true" >> $GITHUB_ENV ; fi
+          # Set Updated flag to check in subsequent steps
+          if [ "$shield_types_updated" -gt 0 ] ; then echo "SHIELDS_UPDATED=true" >> $GITHUB_ENV ; fi
       
       - name: Config committer
-        if: env.shields_updated == 'true'
+        if: env.SHIELDS_UPDATED == 'true'
         run: |
           gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
           git config --global commit.gpgsign true
@@ -249,10 +249,10 @@ jobs:
           git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"
 
       - name: Push changes to adamlui/ai-web-extensions
-        if: env.shields_updated == 'true'
+        if: env.SHIELDS_UPDATED == 'true'
         run: |
           cd ${{ github.workspace }}/adamlui/ai-web-extensions
           git pull # again to sync w/ concurrent workflow updates
           git add .
-          git commit -n -m "${{ env.commit_msg }}" || true
+          git commit -n -m "${{ env.COMMIT_MSG }}" || true
           git push
